# Generated by Django 4.2.13 on 2024-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code_link',
            field=models.URLField(default='https://github.com/Ayobami6/portfolio_api'),
        ),
    ]
