# Generated by Django 4.2.13 on 2024-06-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='project.project'),
        ),
    ]
